[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nova-ai-assistant"
version = "0.1.0"
description = "Simple Nova AI assistant project"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
